// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIl-RgVHblRZx-MZHlhRWEOK90iw6eEyI',
    appId: '1:889047904404:web:15008b6e4ff1cfbfa5c481',
    messagingSenderId: '889047904404',
    projectId: 'gallerypos',
    authDomain: 'gallerypos.firebaseapp.com',
    storageBucket: 'gallerypos.firebasestorage.app',
    measurementId: 'G-ZY557LYH1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQm-CFYl5PZ9qWGVnVb5BF66cNjYl-8Qg',
    appId: '1:889047904404:android:bf00294bd57f3ae1a5c481',
    messagingSenderId: '889047904404',
    projectId: 'gallerypos',
    storageBucket: 'gallerypos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2W8COyQKDVdD4FhTRnUn5FQU5v_DYGgE',
    appId: '1:889047904404:ios:b72a611d54e80e13a5c481',
    messagingSenderId: '889047904404',
    projectId: 'gallerypos',
    storageBucket: 'gallerypos.firebasestorage.app',
    iosBundleId: 'store.gogama.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIl-RgVHblRZx-MZHlhRWEOK90iw6eEyI',
    appId: '1:889047904404:web:15008b6e4ff1cfbfa5c481',
    messagingSenderId: '889047904404',
    projectId: 'gallerypos',
    authDomain: 'gallerypos.firebaseapp.com',
    storageBucket: 'gallerypos.firebasestorage.app',
    measurementId: 'G-ZY557LYH1W',
  );
}
